version: "3.7"
services:
  trino:
    depends_on:
      - trino-minio
    healthcheck:
      interval: 5s
      retries: 6
      test:
        - CMD-SHELL
        - trino --execute 'SELECT 1 AS one'
      timeout: 30s
    image: trinodb/trino:405
    ports:
      - 8080:8080
    networks:
      - trino
    volumes:
      - $PWD/trino/etc:/etc/trino/:ro
  trino-hive-mariadb:
    image: 'mariadb:latest'
    hostname: trino-hive-mariadb
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    networks:
      - trino

  trino-hive-metastore:
    hostname: trino-hive-metastore
    image: 'bitsondatadev/hive-metastore:latest'
    ports:
      - '9083:9083'
    volumes:
      - $PWD/hive/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: trino-hive-mariadb
    depends_on:
      - trino-hive-mariadb
    networks:
      - trino
  trino-minio:
    hostname: trino-minio
    image: 'minio/minio:latest'
    container_name: trino-minio
    ports:
      - "9001:9001"
      - "9000:9000"
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    networks:
      - trino
  trino-mc:
    depends_on:
      - trino-minio
    image: minio/mc
    container_name: trino-mc
    entrypoint: |
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://trino-minio:9000 minio minio123) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/dev;
      /usr/bin/mc mb minio/dev;
      /usr/bin/mc anonymous set public minio/dev;
      exit 0";
    networks:
      - trino

volumes:
  minio-data:
    driver: local

networks:
  postgres:
  trino:
